//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home_page: Home_Page;
  home_pageConnection: Home_PageConnection;
  about_page: About_Page;
  about_pageConnection: About_PageConnection;
  programs_page: Programs_Page;
  programs_pageConnection: Programs_PageConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
  courses: Courses;
  coursesConnection: CoursesConnection;
  blogs: Blogs;
  blogsConnection: BlogsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHome_PageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHome_PageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_PageFilter>;
};


export type QueryAbout_PageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAbout_PageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<About_PageFilter>;
};


export type QueryPrograms_PageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPrograms_PageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Programs_PageFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryCoursesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCoursesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CoursesFilter>;
};


export type QueryBlogsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogsFilter>;
};

export type DocumentFilter = {
  home_page?: InputMaybe<Home_PageFilter>;
  about_page?: InputMaybe<About_PageFilter>;
  programs_page?: InputMaybe<Programs_PageFilter>;
  settings?: InputMaybe<SettingsFilter>;
  courses?: InputMaybe<CoursesFilter>;
  blogs?: InputMaybe<BlogsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home_Page | About_Page | Programs_Page | Settings | Courses | Blogs | Folder;

export type Home_PageFeature_Boxes = {
  __typename?: 'Home_pageFeature_boxes';
  title?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type Home_Page = Node & Document & {
  __typename?: 'Home_page';
  slide1_image?: Maybe<Scalars['String']['output']>;
  slide1_title?: Maybe<Scalars['String']['output']>;
  slide1_subtitle?: Maybe<Scalars['String']['output']>;
  slide1_text?: Maybe<Scalars['String']['output']>;
  slide2_image?: Maybe<Scalars['String']['output']>;
  slide2_title?: Maybe<Scalars['String']['output']>;
  slide2_subtitle?: Maybe<Scalars['String']['output']>;
  slide2_text?: Maybe<Scalars['String']['output']>;
  welcome_title?: Maybe<Scalars['String']['output']>;
  vision?: Maybe<Scalars['String']['output']>;
  mission?: Maybe<Scalars['String']['output']>;
  feature_boxes?: Maybe<Array<Maybe<Home_PageFeature_Boxes>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Home_PageFeature_BoxesFilter = {
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type Home_PageFilter = {
  slide1_image?: InputMaybe<ImageFilter>;
  slide1_title?: InputMaybe<StringFilter>;
  slide1_subtitle?: InputMaybe<StringFilter>;
  slide1_text?: InputMaybe<StringFilter>;
  slide2_image?: InputMaybe<ImageFilter>;
  slide2_title?: InputMaybe<StringFilter>;
  slide2_subtitle?: InputMaybe<StringFilter>;
  slide2_text?: InputMaybe<StringFilter>;
  welcome_title?: InputMaybe<StringFilter>;
  vision?: InputMaybe<StringFilter>;
  mission?: InputMaybe<StringFilter>;
  feature_boxes?: InputMaybe<Home_PageFeature_BoxesFilter>;
};

export type Home_PageConnectionEdges = {
  __typename?: 'Home_pageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home_Page>;
};

export type Home_PageConnection = Connection & {
  __typename?: 'Home_pageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Home_PageConnectionEdges>>>;
};

export type About_PageCore_Team = {
  __typename?: 'About_pageCore_team';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  initials?: Maybe<Scalars['String']['output']>;
  country?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
};

export type About_PagePartnerships = {
  __typename?: 'About_pagePartnerships';
  title?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type About_PageCommunity_Groups = {
  __typename?: 'About_pageCommunity_groups';
  title?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type About_Page = Node & Document & {
  __typename?: 'About_page';
  vision?: Maybe<Scalars['String']['output']>;
  mission?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Scalars['String']['output']>;
  what_we_do?: Maybe<Scalars['String']['output']>;
  company_profile?: Maybe<Scalars['String']['output']>;
  our_impact?: Maybe<Scalars['String']['output']>;
  why_choose_vvi?: Maybe<Scalars['String']['output']>;
  founder_name?: Maybe<Scalars['String']['output']>;
  founder_title?: Maybe<Scalars['String']['output']>;
  founder_image?: Maybe<Scalars['String']['output']>;
  founder_bio?: Maybe<Scalars['String']['output']>;
  founder_quote?: Maybe<Scalars['String']['output']>;
  moses_name?: Maybe<Scalars['String']['output']>;
  moses_title?: Maybe<Scalars['String']['output']>;
  moses_image?: Maybe<Scalars['String']['output']>;
  moses_bio?: Maybe<Scalars['String']['output']>;
  core_team?: Maybe<Array<Maybe<About_PageCore_Team>>>;
  partnerships?: Maybe<Array<Maybe<About_PagePartnerships>>>;
  community_groups?: Maybe<Array<Maybe<About_PageCommunity_Groups>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type About_PageCore_TeamFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  initials?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type About_PagePartnershipsFilter = {
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type About_PageCommunity_GroupsFilter = {
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type About_PageFilter = {
  vision?: InputMaybe<StringFilter>;
  mission?: InputMaybe<StringFilter>;
  values?: InputMaybe<StringFilter>;
  what_we_do?: InputMaybe<StringFilter>;
  company_profile?: InputMaybe<StringFilter>;
  our_impact?: InputMaybe<StringFilter>;
  why_choose_vvi?: InputMaybe<StringFilter>;
  founder_name?: InputMaybe<StringFilter>;
  founder_title?: InputMaybe<StringFilter>;
  founder_image?: InputMaybe<ImageFilter>;
  founder_bio?: InputMaybe<StringFilter>;
  founder_quote?: InputMaybe<StringFilter>;
  moses_name?: InputMaybe<StringFilter>;
  moses_title?: InputMaybe<StringFilter>;
  moses_image?: InputMaybe<ImageFilter>;
  moses_bio?: InputMaybe<StringFilter>;
  core_team?: InputMaybe<About_PageCore_TeamFilter>;
  partnerships?: InputMaybe<About_PagePartnershipsFilter>;
  community_groups?: InputMaybe<About_PageCommunity_GroupsFilter>;
};

export type About_PageConnectionEdges = {
  __typename?: 'About_pageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About_Page>;
};

export type About_PageConnection = Connection & {
  __typename?: 'About_pageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<About_PageConnectionEdges>>>;
};

export type Programs_PagePrograms = {
  __typename?: 'Programs_pagePrograms';
  id?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  short?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
};

export type Programs_Page = Node & Document & {
  __typename?: 'Programs_page';
  programs_hero_title?: Maybe<Scalars['String']['output']>;
  programs?: Maybe<Array<Maybe<Programs_PagePrograms>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Programs_PageProgramsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  short?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
};

export type Programs_PageFilter = {
  programs_hero_title?: InputMaybe<StringFilter>;
  programs?: InputMaybe<Programs_PageProgramsFilter>;
};

export type Programs_PageConnectionEdges = {
  __typename?: 'Programs_pageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Programs_Page>;
};

export type Programs_PageConnection = Connection & {
  __typename?: 'Programs_pageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Programs_PageConnectionEdges>>>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  primary_color?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SettingsFilter = {
  primary_color?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Courses = Node & Document & {
  __typename?: 'Courses';
  title: Scalars['String']['output'];
  category: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CoursesFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type CoursesConnectionEdges = {
  __typename?: 'CoursesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Courses>;
};

export type CoursesConnection = Connection & {
  __typename?: 'CoursesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CoursesConnectionEdges>>>;
};

export type Blogs = Node & Document & {
  __typename?: 'Blogs';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogsConnectionEdges = {
  __typename?: 'BlogsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blogs>;
};

export type BlogsConnection = Connection & {
  __typename?: 'BlogsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome_page: Home_Page;
  createHome_page: Home_Page;
  updateAbout_page: About_Page;
  createAbout_page: About_Page;
  updatePrograms_page: Programs_Page;
  createPrograms_page: Programs_Page;
  updateSettings: Settings;
  createSettings: Settings;
  updateCourses: Courses;
  createCourses: Courses;
  updateBlogs: Blogs;
  createBlogs: Blogs;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHome_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_PageMutation;
};


export type MutationCreateHome_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_PageMutation;
};


export type MutationUpdateAbout_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: About_PageMutation;
};


export type MutationCreateAbout_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: About_PageMutation;
};


export type MutationUpdatePrograms_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: Programs_PageMutation;
};


export type MutationCreatePrograms_PageArgs = {
  relativePath: Scalars['String']['input'];
  params: Programs_PageMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateCoursesArgs = {
  relativePath: Scalars['String']['input'];
  params: CoursesMutation;
};


export type MutationCreateCoursesArgs = {
  relativePath: Scalars['String']['input'];
  params: CoursesMutation;
};


export type MutationUpdateBlogsArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogsMutation;
};


export type MutationCreateBlogsArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogsMutation;
};

export type DocumentUpdateMutation = {
  home_page?: InputMaybe<Home_PageMutation>;
  about_page?: InputMaybe<About_PageMutation>;
  programs_page?: InputMaybe<Programs_PageMutation>;
  settings?: InputMaybe<SettingsMutation>;
  courses?: InputMaybe<CoursesMutation>;
  blogs?: InputMaybe<BlogsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home_page?: InputMaybe<Home_PageMutation>;
  about_page?: InputMaybe<About_PageMutation>;
  programs_page?: InputMaybe<Programs_PageMutation>;
  settings?: InputMaybe<SettingsMutation>;
  courses?: InputMaybe<CoursesMutation>;
  blogs?: InputMaybe<BlogsMutation>;
};

export type Home_PageFeature_BoxesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type Home_PageMutation = {
  slide1_image?: InputMaybe<Scalars['String']['input']>;
  slide1_title?: InputMaybe<Scalars['String']['input']>;
  slide1_subtitle?: InputMaybe<Scalars['String']['input']>;
  slide1_text?: InputMaybe<Scalars['String']['input']>;
  slide2_image?: InputMaybe<Scalars['String']['input']>;
  slide2_title?: InputMaybe<Scalars['String']['input']>;
  slide2_subtitle?: InputMaybe<Scalars['String']['input']>;
  slide2_text?: InputMaybe<Scalars['String']['input']>;
  welcome_title?: InputMaybe<Scalars['String']['input']>;
  vision?: InputMaybe<Scalars['String']['input']>;
  mission?: InputMaybe<Scalars['String']['input']>;
  feature_boxes?: InputMaybe<Array<InputMaybe<Home_PageFeature_BoxesMutation>>>;
};

export type About_PageCore_TeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  initials?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type About_PagePartnershipsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type About_PageCommunity_GroupsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type About_PageMutation = {
  vision?: InputMaybe<Scalars['String']['input']>;
  mission?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Scalars['String']['input']>;
  what_we_do?: InputMaybe<Scalars['String']['input']>;
  company_profile?: InputMaybe<Scalars['String']['input']>;
  our_impact?: InputMaybe<Scalars['String']['input']>;
  why_choose_vvi?: InputMaybe<Scalars['String']['input']>;
  founder_name?: InputMaybe<Scalars['String']['input']>;
  founder_title?: InputMaybe<Scalars['String']['input']>;
  founder_image?: InputMaybe<Scalars['String']['input']>;
  founder_bio?: InputMaybe<Scalars['String']['input']>;
  founder_quote?: InputMaybe<Scalars['String']['input']>;
  moses_name?: InputMaybe<Scalars['String']['input']>;
  moses_title?: InputMaybe<Scalars['String']['input']>;
  moses_image?: InputMaybe<Scalars['String']['input']>;
  moses_bio?: InputMaybe<Scalars['String']['input']>;
  core_team?: InputMaybe<Array<InputMaybe<About_PageCore_TeamMutation>>>;
  partnerships?: InputMaybe<Array<InputMaybe<About_PagePartnershipsMutation>>>;
  community_groups?: InputMaybe<Array<InputMaybe<About_PageCommunity_GroupsMutation>>>;
};

export type Programs_PageProgramsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  short?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
};

export type Programs_PageMutation = {
  programs_hero_title?: InputMaybe<Scalars['String']['input']>;
  programs?: InputMaybe<Array<InputMaybe<Programs_PageProgramsMutation>>>;
};

export type SettingsMutation = {
  primary_color?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
};

export type CoursesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type BlogsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Home_PagePartsFragment = { __typename: 'Home_page', slide1_image?: string | null, slide1_title?: string | null, slide1_subtitle?: string | null, slide1_text?: string | null, slide2_image?: string | null, slide2_title?: string | null, slide2_subtitle?: string | null, slide2_text?: string | null, welcome_title?: string | null, vision?: string | null, mission?: string | null, feature_boxes?: Array<{ __typename: 'Home_pageFeature_boxes', title?: string | null, icon?: string | null, desc?: string | null } | null> | null };

export type About_PagePartsFragment = { __typename: 'About_page', vision?: string | null, mission?: string | null, values?: string | null, what_we_do?: string | null, company_profile?: string | null, our_impact?: string | null, why_choose_vvi?: string | null, founder_name?: string | null, founder_title?: string | null, founder_image?: string | null, founder_bio?: string | null, founder_quote?: string | null, moses_name?: string | null, moses_title?: string | null, moses_image?: string | null, moses_bio?: string | null, core_team?: Array<{ __typename: 'About_pageCore_team', name?: string | null, title?: string | null, initials?: string | null, country?: string | null, image?: string | null, bio?: string | null } | null> | null, partnerships?: Array<{ __typename: 'About_pagePartnerships', title?: string | null, icon?: string | null, desc?: string | null } | null> | null, community_groups?: Array<{ __typename: 'About_pageCommunity_groups', title?: string | null, icon?: string | null, desc?: string | null } | null> | null };

export type Programs_PagePartsFragment = { __typename: 'Programs_page', programs_hero_title?: string | null, programs?: Array<{ __typename: 'Programs_pagePrograms', id?: string | null, title?: string | null, icon?: string | null, short?: string | null, details?: string | null } | null> | null };

export type SettingsPartsFragment = { __typename: 'Settings', primary_color?: string | null, email?: string | null, phone?: string | null, address?: string | null };

export type CoursesPartsFragment = { __typename: 'Courses', title: string, category: string, icon?: string | null, desc?: string | null };

export type BlogsPartsFragment = { __typename: 'Blogs', title: string, date?: string | null, author?: string | null, image?: string | null, description?: string | null, body?: any | null };

export type Home_PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Home_PageQuery = { __typename?: 'Query', home_page: { __typename: 'Home_page', id: string, slide1_image?: string | null, slide1_title?: string | null, slide1_subtitle?: string | null, slide1_text?: string | null, slide2_image?: string | null, slide2_title?: string | null, slide2_subtitle?: string | null, slide2_text?: string | null, welcome_title?: string | null, vision?: string | null, mission?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, feature_boxes?: Array<{ __typename: 'Home_pageFeature_boxes', title?: string | null, icon?: string | null, desc?: string | null } | null> | null } };

export type Home_PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_PageFilter>;
}>;


export type Home_PageConnectionQuery = { __typename?: 'Query', home_pageConnection: { __typename?: 'Home_pageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Home_pageConnectionEdges', cursor: string, node?: { __typename: 'Home_page', id: string, slide1_image?: string | null, slide1_title?: string | null, slide1_subtitle?: string | null, slide1_text?: string | null, slide2_image?: string | null, slide2_title?: string | null, slide2_subtitle?: string | null, slide2_text?: string | null, welcome_title?: string | null, vision?: string | null, mission?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, feature_boxes?: Array<{ __typename: 'Home_pageFeature_boxes', title?: string | null, icon?: string | null, desc?: string | null } | null> | null } | null } | null> | null } };

export type About_PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type About_PageQuery = { __typename?: 'Query', about_page: { __typename: 'About_page', id: string, vision?: string | null, mission?: string | null, values?: string | null, what_we_do?: string | null, company_profile?: string | null, our_impact?: string | null, why_choose_vvi?: string | null, founder_name?: string | null, founder_title?: string | null, founder_image?: string | null, founder_bio?: string | null, founder_quote?: string | null, moses_name?: string | null, moses_title?: string | null, moses_image?: string | null, moses_bio?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, core_team?: Array<{ __typename: 'About_pageCore_team', name?: string | null, title?: string | null, initials?: string | null, country?: string | null, image?: string | null, bio?: string | null } | null> | null, partnerships?: Array<{ __typename: 'About_pagePartnerships', title?: string | null, icon?: string | null, desc?: string | null } | null> | null, community_groups?: Array<{ __typename: 'About_pageCommunity_groups', title?: string | null, icon?: string | null, desc?: string | null } | null> | null } };

export type About_PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<About_PageFilter>;
}>;


export type About_PageConnectionQuery = { __typename?: 'Query', about_pageConnection: { __typename?: 'About_pageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'About_pageConnectionEdges', cursor: string, node?: { __typename: 'About_page', id: string, vision?: string | null, mission?: string | null, values?: string | null, what_we_do?: string | null, company_profile?: string | null, our_impact?: string | null, why_choose_vvi?: string | null, founder_name?: string | null, founder_title?: string | null, founder_image?: string | null, founder_bio?: string | null, founder_quote?: string | null, moses_name?: string | null, moses_title?: string | null, moses_image?: string | null, moses_bio?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, core_team?: Array<{ __typename: 'About_pageCore_team', name?: string | null, title?: string | null, initials?: string | null, country?: string | null, image?: string | null, bio?: string | null } | null> | null, partnerships?: Array<{ __typename: 'About_pagePartnerships', title?: string | null, icon?: string | null, desc?: string | null } | null> | null, community_groups?: Array<{ __typename: 'About_pageCommunity_groups', title?: string | null, icon?: string | null, desc?: string | null } | null> | null } | null } | null> | null } };

export type Programs_PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Programs_PageQuery = { __typename?: 'Query', programs_page: { __typename: 'Programs_page', id: string, programs_hero_title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, programs?: Array<{ __typename: 'Programs_pagePrograms', id?: string | null, title?: string | null, icon?: string | null, short?: string | null, details?: string | null } | null> | null } };

export type Programs_PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Programs_PageFilter>;
}>;


export type Programs_PageConnectionQuery = { __typename?: 'Query', programs_pageConnection: { __typename?: 'Programs_pageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Programs_pageConnectionEdges', cursor: string, node?: { __typename: 'Programs_page', id: string, programs_hero_title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, programs?: Array<{ __typename: 'Programs_pagePrograms', id?: string | null, title?: string | null, icon?: string | null, short?: string | null, details?: string | null } | null> | null } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, primary_color?: string | null, email?: string | null, phone?: string | null, address?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, primary_color?: string | null, email?: string | null, phone?: string | null, address?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CoursesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CoursesQuery = { __typename?: 'Query', courses: { __typename: 'Courses', id: string, title: string, category: string, icon?: string | null, desc?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CoursesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CoursesFilter>;
}>;


export type CoursesConnectionQuery = { __typename?: 'Query', coursesConnection: { __typename?: 'CoursesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CoursesConnectionEdges', cursor: string, node?: { __typename: 'Courses', id: string, title: string, category: string, icon?: string | null, desc?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BlogsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogsQuery = { __typename?: 'Query', blogs: { __typename: 'Blogs', id: string, title: string, date?: string | null, author?: string | null, image?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogsFilter>;
}>;


export type BlogsConnectionQuery = { __typename?: 'Query', blogsConnection: { __typename?: 'BlogsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogsConnectionEdges', cursor: string, node?: { __typename: 'Blogs', id: string, title: string, date?: string | null, author?: string | null, image?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Home_PagePartsFragmentDoc = gql`
    fragment Home_pageParts on Home_page {
  __typename
  slide1_image
  slide1_title
  slide1_subtitle
  slide1_text
  slide2_image
  slide2_title
  slide2_subtitle
  slide2_text
  welcome_title
  vision
  mission
  feature_boxes {
    __typename
    title
    icon
    desc
  }
}
    `;
export const About_PagePartsFragmentDoc = gql`
    fragment About_pageParts on About_page {
  __typename
  vision
  mission
  values
  what_we_do
  company_profile
  our_impact
  why_choose_vvi
  founder_name
  founder_title
  founder_image
  founder_bio
  founder_quote
  moses_name
  moses_title
  moses_image
  moses_bio
  core_team {
    __typename
    name
    title
    initials
    country
    image
    bio
  }
  partnerships {
    __typename
    title
    icon
    desc
  }
  community_groups {
    __typename
    title
    icon
    desc
  }
}
    `;
export const Programs_PagePartsFragmentDoc = gql`
    fragment Programs_pageParts on Programs_page {
  __typename
  programs_hero_title
  programs {
    __typename
    id
    title
    icon
    short
    details
  }
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  primary_color
  email
  phone
  address
}
    `;
export const CoursesPartsFragmentDoc = gql`
    fragment CoursesParts on Courses {
  __typename
  title
  category
  icon
  desc
}
    `;
export const BlogsPartsFragmentDoc = gql`
    fragment BlogsParts on Blogs {
  __typename
  title
  date
  author
  image
  description
  body
}
    `;
export const Home_PageDocument = gql`
    query home_page($relativePath: String!) {
  home_page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Home_pageParts
  }
}
    ${Home_PagePartsFragmentDoc}`;
export const Home_PageConnectionDocument = gql`
    query home_pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Home_pageFilter) {
  home_pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Home_pageParts
      }
    }
  }
}
    ${Home_PagePartsFragmentDoc}`;
export const About_PageDocument = gql`
    query about_page($relativePath: String!) {
  about_page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...About_pageParts
  }
}
    ${About_PagePartsFragmentDoc}`;
export const About_PageConnectionDocument = gql`
    query about_pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: About_pageFilter) {
  about_pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...About_pageParts
      }
    }
  }
}
    ${About_PagePartsFragmentDoc}`;
export const Programs_PageDocument = gql`
    query programs_page($relativePath: String!) {
  programs_page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Programs_pageParts
  }
}
    ${Programs_PagePartsFragmentDoc}`;
export const Programs_PageConnectionDocument = gql`
    query programs_pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Programs_pageFilter) {
  programs_pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Programs_pageParts
      }
    }
  }
}
    ${Programs_PagePartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const CoursesDocument = gql`
    query courses($relativePath: String!) {
  courses(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CoursesParts
  }
}
    ${CoursesPartsFragmentDoc}`;
export const CoursesConnectionDocument = gql`
    query coursesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CoursesFilter) {
  coursesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CoursesParts
      }
    }
  }
}
    ${CoursesPartsFragmentDoc}`;
export const BlogsDocument = gql`
    query blogs($relativePath: String!) {
  blogs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogsParts
  }
}
    ${BlogsPartsFragmentDoc}`;
export const BlogsConnectionDocument = gql`
    query blogsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogsFilter) {
  blogsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogsParts
      }
    }
  }
}
    ${BlogsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home_page(variables: Home_PageQueryVariables, options?: C): Promise<{data: Home_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_PageQueryVariables, query: string}> {
        return requester<{data: Home_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_PageQueryVariables, query: string}, Home_PageQueryVariables>(Home_PageDocument, variables, options);
      },
    home_pageConnection(variables?: Home_PageConnectionQueryVariables, options?: C): Promise<{data: Home_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_PageConnectionQueryVariables, query: string}> {
        return requester<{data: Home_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_PageConnectionQueryVariables, query: string}, Home_PageConnectionQueryVariables>(Home_PageConnectionDocument, variables, options);
      },
    about_page(variables: About_PageQueryVariables, options?: C): Promise<{data: About_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageQueryVariables, query: string}> {
        return requester<{data: About_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageQueryVariables, query: string}, About_PageQueryVariables>(About_PageDocument, variables, options);
      },
    about_pageConnection(variables?: About_PageConnectionQueryVariables, options?: C): Promise<{data: About_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageConnectionQueryVariables, query: string}> {
        return requester<{data: About_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: About_PageConnectionQueryVariables, query: string}, About_PageConnectionQueryVariables>(About_PageConnectionDocument, variables, options);
      },
    programs_page(variables: Programs_PageQueryVariables, options?: C): Promise<{data: Programs_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Programs_PageQueryVariables, query: string}> {
        return requester<{data: Programs_PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Programs_PageQueryVariables, query: string}, Programs_PageQueryVariables>(Programs_PageDocument, variables, options);
      },
    programs_pageConnection(variables?: Programs_PageConnectionQueryVariables, options?: C): Promise<{data: Programs_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Programs_PageConnectionQueryVariables, query: string}> {
        return requester<{data: Programs_PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Programs_PageConnectionQueryVariables, query: string}, Programs_PageConnectionQueryVariables>(Programs_PageConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    courses(variables: CoursesQueryVariables, options?: C): Promise<{data: CoursesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CoursesQueryVariables, query: string}> {
        return requester<{data: CoursesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CoursesQueryVariables, query: string}, CoursesQueryVariables>(CoursesDocument, variables, options);
      },
    coursesConnection(variables?: CoursesConnectionQueryVariables, options?: C): Promise<{data: CoursesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CoursesConnectionQueryVariables, query: string}> {
        return requester<{data: CoursesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CoursesConnectionQueryVariables, query: string}, CoursesConnectionQueryVariables>(CoursesConnectionDocument, variables, options);
      },
    blogs(variables: BlogsQueryVariables, options?: C): Promise<{data: BlogsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogsQueryVariables, query: string}> {
        return requester<{data: BlogsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogsQueryVariables, query: string}, BlogsQueryVariables>(BlogsDocument, variables, options);
      },
    blogsConnection(variables?: BlogsConnectionQueryVariables, options?: C): Promise<{data: BlogsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogsConnectionQueryVariables, query: string}> {
        return requester<{data: BlogsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogsConnectionQueryVariables, query: string}, BlogsConnectionQueryVariables>(BlogsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  